### ISSUE TITLE
Creeps crowd around the source and get stuck

### ISSUE THREAD

**Issue by seth10** [sethten/screeps#6]
When a creep has no energy ([`creep.carry.energy == 0`](https://github.com/sethten/screeps/blob/02414899f263bffd7b00ef6b090993cededea284/main.js#L25)), it's task is set to 'harvest'. Because there is only one source to harvest, it is quite possible for 5 creeps ([`Memory.MAX_CREEPS = 5;`](https://github.com/sethten/screeps/blob/02414899f263bffd7b00ef6b090993cededea284/main.js#L1)) to be finished hauling and all crowded around trying to harvest the source. In this case, it is quite plausible for them to get stuck in each other's pathfinding. When the creep currently harvesting finishes it will not be able to move away from the source. This may resolve itself because some of the creeps will despawn at different times and eventually get free, but this will cause a lot of wasted ticks.

**Comment by seth10** [comment]
There is still somewhat of a crowding issue. Having built a Storage structure diagonally from the wall seems to help though. This gives the creep that has finished harvesting an alternate route to move away. The pathfinding only seems to take this longer path if two creeps are crowding around blocking the way.

I believe what is happening is the following: creepA is at [15,43] and creepB is at [16,43]. creepA is trying to move to the room controller. Because [16,43] is occupied by creepB, it tries moving diagonally to [16,44]. creepB is trying to get to [15,43] to harvest, but that space is occupied by creepA. Trying to find another route, it instead moves to [16,44]. This means both creeps are trying to move to the same space each tick. When creepC comes down and occupies [16,44], creepA takes the longer route starting with [14,44] because that is the only available adjacent tile.

This is like you walking towards someone in a hallway. You both make a move to the left (your left, his or her right) to get out of the other's way. Seeing you're still walking towards each other, you both make a motion for the other direction, possibly repeating this awkward situation a few iterations.

Having additional creeps, perhaps one more, might actually help, because more often will two will gather to push the stuck harvester out (force it to pathfind another way). Too many will counteract the benefit though, creating the possibility of all three adjacent tiles becoming occupied.

**Comment by SSzretter** [comment]
I think this is still an issue.  In this screen shot, it's hard to see but the creep that is saying 'h t' down in the bottom left has finished harvesting and is just sitting there not moving.  Yet the code is basically the same as from the tutorial for a harvester - it hits the else statement because it is full of energy and now it's going to go transfer.   So I am guessing it's not moving because of all the other creeps around it.   Also of course those creeps cant get in there because he is in the way...    Eventually some creeps died and he was able to move...

![image](https://cloud.githubusercontent.com/assets/198003/19869575/465a0ffe-9f83-11e6-9d04-221fa83a89a5.png)

 var targets = creep.room.find(FIND_STRUCTURES, {
                    filter: (structure) => {
                        return (structure.structureType == STRUCTURE_EXTENSION ||
                                structure.structureType == STRUCTURE_SPAWN ||
                                structure.structureType == STRUCTURE_TOWER) && structure.energy < structure.energyCapacity;
                    }
            });
            if(targets.length > 0) {
                if(creep.transfer(targets[0], RESOURCE_ENERGY) == ERR_NOT_IN_RANGE) {
                    creep.moveTo(targets[0]);
                    creep.say("h t");
                }
                else
                {
                    console.log('transfer target prob or done');
                   creep.memory.hsource=Math.floor(Math.random() \* sources.length);  // pick a new random source
                }
            }

**Comment by seth10** [comment]
Just making sure, are you using hsource somewhere else? I do believe you are experience the same issue I had run in to though. The pathfinding for multiple creeps is resolving to targeting the same cell.

**Comment by SSzretter** [comment]
This is the full source

var roleHarvester = {

```
/** @param {Creep} creep **/
run: function(creep) {
    var sources =   creep.room.find(FIND_SOURCES); //creep.pos.findInRange(FIND_SOURCES);  

    if(creep.carry.energy < creep.carryCapacity) 
    {


        if(creep.memory.hsource>=0)  // what source do we want (to prevent getting stuck)
        {
           // we are good

        }
        else
        {
            creep.memory.hsource=Math.floor(Math.random() * sources.length);
        }

        if(creep.harvest(sources[creep.memory.hsource]) == ERR_NOT_IN_RANGE) {   // this was sources[0]
            creep.moveTo(sources[creep.memory.hsource]);
            creep.say("h h "+ creep.memory.hsource);
        }
    }
    else {
        var targets = creep.room.find(FIND_STRUCTURES, {
                filter: (structure) => {
                    return (structure.structureType == STRUCTURE_EXTENSION ||
                            structure.structureType == STRUCTURE_SPAWN ||
                            structure.structureType == STRUCTURE_TOWER) && structure.energy < structure.energyCapacity;
                }
        });
        if(targets.length > 0) {
            if(creep.transfer(targets[0], RESOURCE_ENERGY) == ERR_NOT_IN_RANGE) {
                creep.moveTo(targets[0]);
                creep.say("h t");
            }
            else
            {
                console.log('transfer target prob or done');   // it is not getting here
               creep.memory.hsource=Math.floor(Math.random() * sources.length);  // pick a new random source
            }
        }
    }
}
```

};

module.exports = roleHarvester;

**Comment by seth10** [comment]
Cool, I wish you luck! Post back here if you find a solution that works for you :) Happy scripting!
